services:
    php:
        image: php:8.3-fpm
        container_name: portfolio_php
        volumes:
            - .:/var/www/html
        working_dir: /var/www/html

    nginx:
        image: nginx:latest
        container_name: portfolio_nginx
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
